/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2015-2019
     \\/     M anipulation  | Matteo Icardi, Federico Municchi, Max Akira Kokobun
-------------------------------------------------------------------------------
License
    This file is derivative work of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.



Application
    binaryReactionFoam

Description
    Unstead solver for incompressible, suspensions flow of particles
    generated by the reaction of two scalars.
    A+B->C with chi = 1/2(A-B) and xi = 1/2(A+B) and psi=C
    xi, chi are concentrations, c is a volume fraction
    Using Ferry Balachandar model for slip velocity

\*---------------------------------------------------------------------------*/

#include "fvCFD.H"
#include "pimpleControl.H"
#include "CorrectPhi.H"
#include "fvOptions.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
#   include "postProcess.H"

#   include "setRootCaseLists.H"
#   include "createTime.H"
#   include "createTimeControls.H"
#   include "createMesh.H"
#   include "initContinuityErrs.H"
#   include "readGravitationalAcceleration.H"
#   include "createFields.H"
#   include "createUfIfPresent.H"
#   include "CourantNo.H"
#   include "setInitialDeltaT.H"

    pimpleControl pimple(mesh);


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    Info<< "\nStarting time loop\n" << endl;

    while (runTime.run())
    {

        #include "CourantNo.H"
        #include "setDeltaT.H"
        runTime++;

        Info<< "Time = " << runTime.timeName() << nl << endl;

        // --- Pressure-velocity PIMPLE corrector loop
        while (pimple.loop())
        {

            volTensorField Gr(fvc::grad(U));

            //- Generalised suspension viscosity
            //- Standard Models
            //- --------------------------------
            //  Morris Boulay (1999)
            //  Ca = 0
            //  Cb = 2.5
            //  Cc = 0.1
            //
            //  Maron and Sisko (1957)
            //  Ca = -1
            //  Cb = 0
            //  Cc = 1
            //- --------------------------------

            nu = nu0 *
            (
                Ca
              + Cb*psi*pow( (scalar(1.0)- (psi/cm)), -scalar(1.0))
              + Cc*pow( (scalar(1.0)- (psi/cm)), -scalar(2.0))
            );

            #include "UEqn.H"

            while(pimple.correct())
            {
              #include "pEqn.H"
            }

            const surfaceScalarField psif(fvc::interpolate(psi));

            // -- solve for the concentrations
            #include "xiEqn.H"  // conserved variable - mixture fraction

            #include "chiEqn.H" // non-conserved variable - progress variable

            // // -- solve for the solid phase
            // #include "updatePhiSlip.H"

            // const surfaceScalarField phic
            //   ("phi",
            //     phi+phislip
            //   );

            // #include "psiEqn.H"


        } // End corrector

        runTime.write();

        Info<< "ExecutionTime = " << runTime.elapsedCpuTime() << " s"
            << "  ClockTime = " << runTime.elapsedClockTime() << " s"
            << nl << endl;
    }

    Info<< "End\n" << endl;

    return(0);
}


// ************************************************************************* //
