#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./CreateMesh
#simpleFoam  # (run this to initialise the pressure and velocity field. to do that change the membrane velocity BC to avoid looking for concentration c, and change timeScheme to steadyState)
runApplication binaryReactionFoam


#------------------------------------------------------------------------------
