/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) The OpenFOAM Foundation, Ltd.
     \\/     M anipulation  | 
-------------------------------------------------------------------------------
  
  Modifications and additional contributions:
  
  MultiForm Group, University of Nottingham
  Copyright (C) Matteo Icardi and collaborators
  Contributions to this file are licensed under the same GPLv3 terms as OpenFOAM.

  This work is based on OpenFOAM, with substantial portions copied, modified, or 
  extended under the GNU General Public License (GPLv3).
  Please refer to the original OpenFOAM copyright notice for the base framework, 
  and to MultiForm Group for new additions or modifications. For the full terms of 
  this license, see <http://www.gnu.org/licenses/>.



Application
    binaryReactionFoam

Description
    Unstead solver for incompressible, suspensions flow of particles
    generated by the reaction of two scalars.
    A+B->C with chi = 1/2(A-B) and xi = 1/2(A+B) and psi=C
    xi, chi are concentrations, c is a volume fraction
    Using Ferry Balachandar model for slip velocity

\*---------------------------------------------------------------------------*/

#include "fvCFD.H"
#include "pimpleControl.H"
#include "CorrectPhi.H"
#include "fvOptions.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
#   include "postProcess.H"

#   include "setRootCaseLists.H"
#   include "createTime.H"
#   include "createTimeControls.H"
#   include "createMesh.H"
#   include "initContinuityErrs.H"
#   include "readGravitationalAcceleration.H"
#   include "createFields.H"
#   include "createUfIfPresent.H"
#   include "CourantNo.H"
#   include "setInitialDeltaT.H"

    pimpleControl pimple(mesh);


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    Info<< "\nStarting time loop\n" << endl;

    while (pimple.loop(runTime))
    {

        #include "CourantNo.H"
        #include "setDeltaT.H"
        runTime++;

        Info<< "Time = " << runTime.timeName() << nl << endl;

        // --- Pressure-velocity PIMPLE corrector loop
        while (pimple.loop())
        {

            volTensorField Gr(fvc::grad(U));

            //- Generalised suspension viscosity
            //- Standard Models
            //- --------------------------------
            //  Morris Boulay (1999)
            //  Ca = 0
            //  Cb = 2.5
            //  Cc = 0.1
            //
            //  Maron and Sisko (1957)
            //  Ca = -1
            //  Cb = 0
            //  Cc = 1
            //- --------------------------------

            nu = nu0 *
            (
                Ca
              + Cb*psi*pow( (scalar(1.0)- (psi/cm)), -scalar(1.0))
              + Cc*pow( (scalar(1.0)- (psi/cm)), -scalar(2.0))
            );

            #include "UEqn.H"

            while(pimple.correct())
            {
              #include "pEqn.H"
            }

            const surfaceScalarField psif(fvc::interpolate(psi));

            // -- solve for the concentrations
            #include "xiEqn.H"  // conserved variable - mixture fraction

            #include "chiEqn.H" // non-conserved variable - progress variable

            // // -- solve for the solid phase
            // #include "updatePhiSlip.H"

            // const surfaceScalarField phic
            //   ("phi",
            //     phi+phislip
            //   );

            // #include "psiEqn.H"


        } // End corrector

        runTime.write();

        Info<< "ExecutionTime = " << runTime.elapsedCpuTime() << " s"
            << "  ClockTime = " << runTime.elapsedClockTime() << " s"
            << nl << endl;
    }

    Info<< "End\n" << endl;

    return(0);
}


// ************************************************************************* //
